language: cpp

dist: trusty
sudo: false

cache:
  apt: true

compiler:
  - g++
  - clang++

os:
  - linux

addons:
  apt:
    packages:
    - openssl
    - libboost-all-dev
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  
