language: cpp

dist: trusty
sudo: true


cache:
  apt: true

compiler:
  - g++

os:
  - linux

addons:
  sources:
  - ubuntu-toolchain-r
  apt:
    packages:
    - g++-7
    - gcc-7
    - openssl
    - libboost-all-dev
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
script:
  - make

