language: cpp

dist: trusty
sudo: true

cache:
  apt: true

compiler:
  - g++

os:
  - linux

addons:
  sources:
  - ubuntu-toolchain-r-test
  apt:
    packages:
    - g++-7
    - openssl
    - libboost-all-dev
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

