language: cpp

dist: trusty
sudo: true


cache:
  apt: true

compiler:
  - g++

os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - openssl
    - libboost-all-dev
    - cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
  - make

